export const processos = [
    {
        numero: 50866,
        ano: 2021,
        data: '29/06/2022  12:54:54',
        nomeAutor: 'Renato Rezende Rocha Filho',
        tipoAutor: 'Usuario Externo',
        cnpjBeneficiario: '15079629000146',
        nomeBeneficiario: 'FUNDO MUNICIPAL DE ASSISTÊNCIA SOCIAL - FMAS (PILAR/AL)',
        estadoBeneficiario: 'AL',
        codOrgao: 55000,
        nomeOrgao: 'Ministerio Da Cidadania',
        codUo:55901,
        uo: 'Fundo Nacional De Assistencia Social',
        codAcao: '219G',
        numeroProposta: '0001/2022',
        indicadorFnde: '',
        numeroCnes: '',
        tipoObjeto: '',
        objeto: 'Aporte de recursos para custeio do Fundo Municipal de Assistência Social do Município de Pilar/AL',
        justificativa: 'Propomos aqui a ampliação da atuação da proteção básica da política de Assistência Social, em seus serviços referenciados de cadastramento e atualização cadastral do',
        gnd: 3,
        tipoExecucao: '',
        ma: 41,
        valor:1303900,
        etapaAtual: 'Com indicação'

    },
    {
        numero: 51472,
        ano: 2022,
        data: '30/06/2022  19:51:39',
        nomeAutor: 'Luis Miranda',
        tipoAutor: 'Deputado',
        cnpjBeneficiario: '11966608000191',
        nomeBeneficiario: 'FUNDO MUNICIPAL DE SAUDE DE CATANDUVA SP',
        estadoBeneficiario: 'SP',
        codOrgao: 36000,
        nomeOrgao: 'Ministerio Da Saude',
        codUo:36901,
        uo: 'Fundo Nacional De Saude',
        codAcao: '2E90',
        numeroProposta: '',
        indicadorFnde: '',
        numeroCnes: '2058626',
        tipoObjeto: '',
        objeto: 'Incremento Temporário ao Custeio dos Serviços de Assistência Hospitalar e Ambulatorial para Cumprimento de Metas.',
        justificativa: 'Verba destinada ao custeio para atenção especializada de saúde no município de Votuporanga no Estado de São Paulo. A verba é destinada a HOSPITAL MAHATMA GANDHI',
        gnd: 3,
        tipoExecucao: '',
        ma: 41,
        valor:3300000,
        etapaAtual: 'Com indicação'
    },
    {
        numero: 49316,
        ano: 2022,
        data: '23/06/2022  19:17:07',
        nomeAutor: 'Edna Telma Portela',
        tipoAutor: 'Usuario Externo',
        cnpjBeneficiario: '06206659000185',
        nomeBeneficiario: 'SECRETARIA DE ESTADO DA SAUDE DO PIAUI',
        estadoBeneficiario: 'PI',
        codOrgao: 36000,
        nomeOrgao: 'Ministerio Da Saude',
        codUo:36901,
        uo: 'Fundo Nacional De Saude',
        codAcao: '2E90',
        numeroProposta: '',
        indicadorFnde: '',
        numeroCnes: '6300049',
        tipoObjeto: '',
        objeto: 'INCREMENTO TEMPORARIO AO CUSTEIO MAC',
        justificativa: 'APOIO NAS ACOES DE MEDIA E ALTA COMPLEXIDADE NO ESTADO',
        gnd: 3,
        tipoExecucao: '',
        ma: 31,
        valor:3500000,
        etapaAtual: 'Com indicação'
    },
    {
        numero: 45026,
        ano: 2022,
        data: '08/06/2022  12:17:36',
        nomeAutor: 'Fernando Batista Do Nascimento',
        tipoAutor: 'Usuario Externo',
        cnpjBeneficiario: '50644053000113',
        nomeBeneficiario: 'Fundação Zerbini',
        estadoBeneficiario: 'SP',
        codOrgao: 36000,
        nomeOrgao: 'Ministerio Da Saude',
        codUo:36901,
        uo: 'Fundo Nacional De Saude',
        codAcao: '2E90',
        numeroProposta: '',
        indicadorFnde: '',
        numeroCnes: '2071568',
        tipoObjeto: '',
        objeto: 'Custeio para manutenção das atividades de média e alta complexidade do Instituto do Coração do Hospital das Clinicas da Faculdade de Medicina de São Paulo (InCor',
        justificativa: 'Custeio para aquisição de materiais especiais, medicamentos e insumos para cirurgias cardíacas que não são custeados pelo Sistema Único de Saúde - SUS',
        gnd: 3,
        tipoExecucao: '',
        ma: 31,
        valor:1000000,
        etapaAtual: 'Com indicação'
    },
    {
        numero: 42684,
        ano: 2022,
        data: '01/06/2022  11:17:49',
        nomeAutor: 'Marcos Rogério Da Silva Brito',
        tipoAutor: 'Senador',
        cnpjBeneficiario: '26989350018082',
        nomeBeneficiario: 'FUNASA RONDÔNIA',
        estadoBeneficiario: 'RO',
        codOrgao: 36000,
        nomeOrgao: 'Ministerio Da Saude',
        codUo:36211,
        uo: 'Fundo Nacional De Saude',
        codAcao: '21CC',
        numeroProposta: '',
        indicadorFnde: '',
        numeroCnes: '',
        tipoObjeto: '',
        objeto: 'Aquisição de Caminhões',
        justificativa: 'Aquisição de Caminhões  para atender a demanda do município',
        gnd: 4,
        tipoExecucao: '',
        ma: 40,
        valor:4000000,
        etapaAtual: 'Com indicação'
    },
]
